Mensajes

diff --git a/src/messages.sh.in b/src/messages.sh.in
--- a/src/messages.sh.in
+++ b/src/messages.sh.in
@@ -20,10 +20,23 @@
 #   51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 #
 
+shirc_verbosity="0"
+
 #
-# shirc_fatal_error
+# SHIRC ERROR FUNCTIONS
+#   shirc_fatal_error
+#   shirc_error
+#   shirc_warning
+#   shirc_notice
+#   shirc_debug
 #
-# Print an error to stderr, call shirc_finalize and exit
+# Shirc message system. These functions may print out the program name, and the
+# message passed as first parameter.
+#
+# Fatal errors and errors are always printed. The former ones trigger
+# the finalization, with an exit code of 1, of the program. Warnings, notices
+# and debug messages are printed according to the verbosity set (see VERBOSITY
+# FUNCTIONS below).
 #
 # Parameters:
 #   1 -- the error message.
@@ -31,11 +44,65 @@
 # Global variables:
 #   shirc_program_name -- for showing in the message
 #
-fatal_error() {
-    echo 2>&1 "$shirc_program_name: Error: $1"
+
+shirc_fatal_error() {
+    echo 1>&2 "$shirc_program_name: Fatal error: ${FUNCNAME[1]}: $1"
     shirc_finalize
 
     exit 1
 
 }
 
+shirc_error() {
+    echo 1>&2 "$shirc_program_name: error: ${FUNCNAME[1]}: $1"
+
+}
+
+shirc_warning() {
+    test "$shirc_verbosity" -ge "0" &&
+        echo 1>&2 "$shirc_program_name: warning: ${FUNCNAME[1]}: $1"
+
+}
+
+shirc_notice() {
+    test "$shirc_verbosity" -ge "1" &&
+        echo 1>&2 "$shirc_program_name: notice: ${FUNCNAME[1]}: $1"
+
+}
+
+shirc_debug() {
+    test "$shirc_verbosity" -ge "2" &&
+        echo 1>&2 "$shirc_program_name: debug message: ${FUNCNAME[1]}: $1"
+
+}
+
+#
+# VERBOSITY FUNCTIONS
+#
+
+#
+# shirc_set_verbosity
+#
+# Sets the verbosity to the level passed as first parameter.
+#
+# Params:
+#   1 -- the level to set to. One of "QUIET", "NORMAL", "VERBOSE", "DEBUG".
+#
+# Global variables:
+#   shirc_verbosity -- current verbosity level.
+#
+shirc_set_verbosity() {
+    local verb
+
+    verb="$1"
+
+    case "$verb" in
+    "QUIET" ) shirc_verbosity="-1";;
+    "NORMAL" ) shirc_verbosity="0";;
+    "VERBOSE" ) shirc_verbosity="1" ;;
+    "DEBUG" ) shirc_verbosity="2";;
+    * )
+        shirc_error "Incorrect parameter passed to shirc_set_verbosity()";;
+    esac
+
+}
